#!/usr/bin/python
from __future__ import with_statement
import collections
import sys
import dbfUtils


def main():
  if len(sys.argv) != 2:
    print "usage: %s filename.dbf" % (sys.argv[0])
    sys.exit(1)
  with open(sys.argv[1], 'rb') as dbf:
    dbr = dbfUtils.dbfreader(dbf)
    field_names = dbr.next()
    field_specs = dbr.next()
    _db = list(dbr)
  print field_names
  print field_specs
  print len(_db), 'total records'
  counts = [collections.defaultdict(int) for f in field_names]
  for record in _db:
    for count, field in zip(counts, record):
      count[field] += 1
  print 'Number of unique values:'
  for i, (count, name) in enumerate(zip(counts, field_names)):
    nums = len(count)
    if nums == 1:
      value = '(%s)' % record[i]
    else:
      value = ''
    print '%10s: %3d %s' % (name, nums, value)
     

main()
