application: gepy
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /(.*)\.html
  static_files: \1.html
  upload: (.*).html

- url: /
  static_files: gepy.html
  upload: gepy.html

- url: /reverse*
  script: reverse.py

- url: .*
  script: main.py
